version: '3'
services:
    rstudio:
        build:
            context: .
        environment:
            - TZ=Europe/Madrid
            - DISABLE_AUTH=true
            - RENV_PATHS_CACHE=/home/rstudio/.renv/cache
            - PYTHONUSERBASE=/home/rstudio/.pip
        volumes:
            - .:/home/rstudio/work
            - $HOME/.renv:/home/rstudio/.renv/cache
            - $HOME/.TinyTeX:/home/rstudio/.TinyTeX
            - $HOME/.pip:/home/rstudio/.pip